/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppItemCard: typeof import('./src/components/AppItemCard.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BaseButton: typeof import('ui')['BaseButton']
    BaseCard: typeof import('ui')['BaseCard']
    BaseDataTable: typeof import('ui')['BaseDataTable']
    BaseDatePicker: typeof import('ui')['BaseDatePicker']
    BaseDateSelector: typeof import('ui')['BaseDateSelector']
    BaseDialog: typeof import('ui')['BaseDialog']
    BaseInfoField: typeof import('ui')['BaseInfoField']
    BaseInput: typeof import('ui')['BaseInput']
    BasePill: typeof import('ui')['BasePill']
    BlockUI: typeof import('primevue/blockui')['default']
    BookingCard: typeof import('./src/components/BookingCard.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    CourtAdminCard: typeof import('./src/components/CourtAdminCard.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FilterSelectorReservation: typeof import('./src/components/FilterSelectorReservation.vue')['default']
    GroupedList: typeof import('ui')['GroupedList']
    LoginForm: typeof import('ui')['LoginForm']
    Navbar: typeof import('ui')['Navbar']
    NavUserCard: typeof import('ui')['NavUserCard']
    PriceConfigForm: typeof import('./src/components/PriceConfigForm.vue')['default']
    PriceSimulator: typeof import('./src/components/PriceSimulator.vue')['default']
    RegisterForm: typeof import('ui')['RegisterForm']
    ReservationSummary: typeof import('./src/components/ReservationSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleManager: typeof import('ui')['ScheduleManager']
    Timeline: typeof import('primevue/timeline')['default']
    UserCardProfile: typeof import('ui')['UserCardProfile']
  }
}
